# Generated by Django 4.0.1 on 2022-01-26 13:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('status', models.BooleanField(default=False, verbose_name='Contrat signé ?')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Coût')),
                ('payment_due', models.DateTimeField(verbose_name='Date de paiement prévue')),
                ('customer_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='customers.customer', verbose_name='Client')),
                ('sales_contact', models.ForeignKey(blank=True, default=0, limit_choices_to={'group': 'VENTE'}, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='assigned_contract', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur assigné')),
            ],
        ),
    ]
